#! /usr/bin/python3
from glob import glob

BLACKLISTED_DIRS = {
    "env",
    "venv",
    ".env",
    ".venv",
}


def count_lines(filepath):
    return open(filepath).read().count('\n')


if __name__ == '__main__':

    # Omit python files from blacklisted dirs
    python_files = set()
    for python_filepath in glob('**/*.py', recursive=True):
        skip = False
        for blacklisted_dir in BLACKLISTED_DIRS:
            if f"/{blacklisted_dir}/" in python_filepath:
                skip = True
                break
        if not skip:
            python_files.add(python_filepath)

    line_count = {}
    for filepath in python_files:
        line_count[filepath] = count_lines(filepath)

    total_lines = sum(line_count.values())

    # Show LOC per file
    file_pad = max([len(k) for k in line_count.keys()])
    count_pad = max([len(str(v)) for v in line_count.values()])
    for (filename, count) in sorted(tuple(line_count.items()), key=lambda tpl: tpl[1], reverse=True):
        print(f'{filename.ljust(file_pad)} {str(count).rjust(count_pad)}')

    print("---------------------------")
    print(f'Total {"".ljust(file_pad-7)} {str(total_lines).rjust(count_pad)} LOC')
    print(f'Total {"".ljust(file_pad-7)} {str(len(python_files)).rjust(count_pad+1)} files')
