#! /usr/bin/python3
from glob import glob


def count_lines(filepath):
    i = -1
    with open(filepath) as f:
        for i, l in enumerate(f):
            pass
    return i + 1


if __name__ == '__main__':
    python_files = glob('**/*.py', recursive=True)

    line_count = {}
    for filepath in python_files:
        line_count[filepath] = count_lines(filepath)

    total_lines = sum(line_count.values())

    # Show LOC per file
    file_pad = max([len(k) for k in line_count.keys()])
    count_pad = max([len(str(v)) for v in line_count.values()])
    for (filename, count) in sorted(tuple(line_count.items()), key=lambda tpl: tpl[1], reverse=True):
        print(f'{filename.ljust(file_pad)} {str(count).rjust(count_pad)}')

    print("---------------------------")
    print(f'Total {"".ljust(file_pad-7)} {str(total_lines).rjust(count_pad)}')
