#! /usr/bin/python3
import argparse
import os
import re
from glob import glob
from os.path import join, basename, relpath

parser = argparse.ArgumentParser(description='Remove files with regular expression.')
parser.add_argument('regex', type=str, nargs='+', help='one or more regular expressions to match')

parser.add_argument('--keep', dest='keep', default=None, action='store_true', help='keep files matching regular expressions')
parser.add_argument('--remove', dest='remove', default=None, action='store_true', help='remove files matching regular expressions')
parser.add_argument('--move', dest='move', nargs=1, help='remove files matching regular expressions')

parser.add_argument('--dry', '-d', dest='dry', action='store_true', default=False, help='show what would actually happen')
parser.add_argument('--invert-match', '-v', dest='invert_match', action='store_true', default=False)
parser.add_argument('--recursive', '-r', dest='recursive', action='store_true', default=False)
parser.add_argument('--ignore-case', '-i', dest='igore_case', action='store_true', default=False, help='case insensitive')

args = parser.parse_args()

if not (args.remove or args.keep or args.move):
    print('No --keep, --remove or --move passed. Will simply print the matching files.')


def all_files():
    """ Get all offspring files under current directory """
    return glob(join(os.getcwd(), '*'), recursive=True)


def get_matching_files():
    """ Get all files matching the regex """
    all_filepaths = all_files()
    matched = []
    for filepath in all_filepaths:
        filename = basename(filepath)
        for regex in args.regex:
            if args.igore_case:
                matches = re.findall(regex, filename, flags=re.IGNORECASE)
            else:
                matches = re.findall(regex, filename)
            if matches:
                matched.append(filepath)
                break
    if args.invert_match:
        matched = set(all_filepaths) - set(matched)
    return matched


# Simply print matches
def show_matches(matched_files):
    for f in matched_files:
        print(f"✔ {relpath(f)}")
    exit(0)


def move_files(files, dest, dry=True):
    for f in files:
        target = join(dest, basename(f))
        pres = f"{relpath(f)} ➜ {relpath(target)}"
        if dry:
            print(pres)
        else:
            os.replace(f, target)
            print(f"Moved file {pres}")


def delete_files(files, dry=True):
    for f in files:
        if dry:
            print(f"✖ {relpath(f)}")
        else:
            os.remove(f)
            print(f"Deleted {relpath(f)}")


if __name__ == '__main__':
    matched = get_matching_files()
    if args.move:
        move_files(matched, args.move[0], dry=args.dry)
        exit(0)
    elif args.keep or args.remove:
        if args.keep:
            matched = set(all_filepaths) - set(matched)
        delete_files(matched, dry=args.dry)
    else:
        show_matches(matched)
